# Generated by Django 3.2.7 on 2021-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0002_user_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reviewer',
            new_name='is_reviewer',
        ),
    ]
