# Generated by Django 3.2.9 on 2021-11-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
