# Generated by Django 3.2.9 on 2021-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_user_receive_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="receive_notifications",
            field=models.BooleanField(
                default=True, help_text="Would you like to receive email notifications?"
            ),
        ),
    ]
