# Generated by Django 3.2.8 on 2021-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(choices=[('NA', 'Not Assigned'), ('AM', 'AM Session'), ('PM', 'PM Session')], default='NA', max_length=2),
        ),
    ]
