# Generated by Django 4.2.1 on 2023-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0006_user_reviews_done_as_reviewee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rainbow_mode",
            field=models.BooleanField(
                default=False, help_text="Enables a rainbow hue throughout the website."
            ),
        ),
    ]
