# Generated by Django 4.1.3 on 2023-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_user_reviews_done_as_reviewee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gay_mode",
            field=models.BooleanField(
                default=False, help_text="Would you like to enable gay mode?"
            ),
        ),
    ]
