# Generated by Django 3.2.8 on 2021-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0007_alter_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(choices=[('AM', 'AM Session'), ('PM', 'PM Session')], default='AM', max_length=2),
        ),
    ]
