# Generated by Django 3.2.7 on 2021-10-11 12:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Main', '0007_remove_review_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('max_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('max_score', models.FloatField()),
                ('index', models.SmallIntegerField()),
                ('parent_rubric',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubric')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ScoredRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('parent_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.review')),
                ('source_row',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubricrow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('index', models.SmallIntegerField()),
                ('parent_row',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubricrow')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
