# Generated by Django 3.2.9 on 2021-11-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredrow',
            name='parent_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.review'),
        ),
        migrations.AddField(
            model_name='scoredrow',
            name='source_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubricrow'),
        ),
        migrations.AddField(
            model_name='rubricrow',
            name='parent_rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubric'),
        ),
        migrations.AddField(
            model_name='rubriccell',
            name='parent_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.rubricrow'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricrow',
            unique_together={('parent_rubric', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='rubriccell',
            unique_together={('parent_row', 'index')},
        ),
    ]
