# Generated by Django 3.2.7 on 2021-09-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('row_number', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('count_zero', models.BooleanField(default=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('min_score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField()),
                ('score_step', models.PositiveSmallIntegerField()),
                ('parent_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('index', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('parent_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(limit_choices_to={'reviewer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignedUser', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.assignment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.rubric'),
        ),
    ]
