# Generated by Django 3.2.7 on 2021-09-17 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('max_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('max_score', models.FloatField()),
                ('parent_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('parent_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubricrow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoology_id', models.CharField(max_length=10, null=True)),
                ('status', models.IntegerField(choices=[('0', 'Open'), ('1', 'Taken'), ('2', 'Completed')], default='0')),
                ('scores', models.CharField(default='', max_length=100)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rubric', to='Main.rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
