# Generated by Django 3.2.7 on 2021-09-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubriccell',
            name='parent_row',
        ),
        migrations.RemoveField(
            model_name='rubricrow',
            name='parent_rubric',
        ),
        migrations.RemoveField(
            model_name='review',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.DeleteModel(
            name='RubricCell',
        ),
        migrations.DeleteModel(
            name='RubricRow',
        ),
    ]
