# Generated by Django 3.2.7 on 2021-09-30 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0002_remove_rubric_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='data',
        ),
        migrations.AddField(
            model_name='rubric',
            name='max_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RubricRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('max_score', models.FloatField()),
                ('index', models.SmallIntegerField()),
                ('parent_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('index', models.SmallIntegerField()),
                ('parent_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubricrow')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
