# Generated by Django 3.2.9 on 2021-12-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Instructor', '0002_initial'),
        ('Main', '0002_auto_20211214_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rubric',
        ),
        migrations.AddField(
            model_name='review',
            name='rubric',
            field=models.ForeignKey(default=1, help_text='The rubric the reviewer will use to grade your code',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='source_rubric',
                                    to='Instructor.rubric'),
            preserve_default=False,
        ),
    ]
