# Generated by Django 3.2.7 on 2021-10-07 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0003_auto_20210930_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubriccell',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='rubricrow',
            options={'ordering': ['index']},
        ),
    ]
