# Generated by Django 3.2.7 on 2021-10-08 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20211007_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('parent_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.review')),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.rubricrow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
