# Generated by Django 3.2.7 on 2021-10-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_scoredrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
    ]
