# Generated by Django 3.2.7 on 2021-10-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Instructor', '0001_initial'),
        ('Main', '0007_remove_review_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubriccell',
            name='parent_row',
        ),
        migrations.RemoveField(
            model_name='rubricrow',
            name='parent_rubric',
        ),
        migrations.RemoveField(
            model_name='scoredrow',
            name='parent_review',
        ),
        migrations.RemoveField(
            model_name='scoredrow',
            name='source_row',
        ),
        migrations.AlterField(
            model_name='review',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rubric',
                                    to='Instructor.rubric'),
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.DeleteModel(
            name='RubricCell',
        ),
        migrations.DeleteModel(
            name='RubricRow',
        ),
        migrations.DeleteModel(
            name='ScoredRow',
        ),
    ]
