# Generated by Django 3.2.8 on 2021-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0008_auto_20211011_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.IntegerField(default=(0, 'Open')),
        ),
    ]
