# Generated by Django 3.2.8 on 2021-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[('0', 'Open'), ('1', 'Taken'), ('2', 'Completed')], default='0'),
        ),
    ]
