# Generated by Django 3.2.8 on 2021-10-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Taken'), ('C', 'Completed')], default='O', max_length=1),
        ),
    ]
