# Generated by Django 3.2.8 on 2021-10-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_review_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created', '-date_completed']},
        ),
    ]
