# Generated by Django 3.2.8 on 2021-10-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_completed', '-date_created']},
        ),
    ]
