name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - ".github/**"
      - "coverage.svg"
      - "concept/**"   
    branches: [ master ]
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - ".github/**"
      - "coverage.svg"
      - "concept/**"
    branches: [ master ]

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10.0
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install
      - name: Install Github-Specific Dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
            command: install psycopg2 coverage==6.0.2 genbadge[coverage]
      - name: Run tests
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run coverage run
        env:
          STAGE: GH_TEST
      - name: Generate XML
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run coverage xml
      - name: Generate Badge
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run genbadge coverage -i coverage.xml -o coverage.svg
      - name: Verify Changed files
        if: github.ref == 'refs/heads/master'
        uses: tj-actions/verify-changed-files@v6
        id: changed_files
        with:
          files: coverage.svg
      - name: Commit files
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"
      - name: Push changes
        if: steps.changed_files.outputs.files_changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}
      
